{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ngrinder",
    "module": "ngrinder-groovy",
    "version": "3.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "girdxw7affhk7fv3asg7exbdim"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ngrinder",
          "module": "ngrinder-runtime",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "ngrinder-groovy-3.5.1.jar",
          "url": "ngrinder-groovy-3.5.1.jar",
          "size": 43145,
          "sha512": "75d5c4aaebbdb1d40e2567b90623f4c30d91ef7d234c573fdd715823a3f23248b6e0a01118710d547f6324410ad377af7708ed42372be1a6f05a3a7d119c900a",
          "sha256": "3b99481f31670307b48b07493563aaea4287ace5ee697846518c443fcdece609",
          "sha1": "d27ba207d89a48ceed9e645f7e37f397277e36b9",
          "md5": "2df826de8032e248d17f684424e7c3ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ngrinder",
          "module": "ngrinder-runtime",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "ngrinder-groovy-3.5.1.jar",
          "url": "ngrinder-groovy-3.5.1.jar",
          "size": 43145,
          "sha512": "75d5c4aaebbdb1d40e2567b90623f4c30d91ef7d234c573fdd715823a3f23248b6e0a01118710d547f6324410ad377af7708ed42372be1a6f05a3a7d119c900a",
          "sha256": "3b99481f31670307b48b07493563aaea4287ace5ee697846518c443fcdece609",
          "sha1": "d27ba207d89a48ceed9e645f7e37f397277e36b9",
          "md5": "2df826de8032e248d17f684424e7c3ba"
        }
      ]
    }
  ]
}
