# -*- coding:utf-8 -*-

# A simple example using the HTTP plugin that shows the retrieval of a
# single page via HTTP. 
#
# This script is auto generated by ngrinder.
#
# @author ${user.userName}
from net.grinder.script.Grinder import grinder
from net.grinder.script import Test
from net.grinder.plugin.http import HTTPRequest

test1 = Test(1, "Test1")
request1 = test1.wrap(HTTPRequest())

class TestRunner:
	def __call__(self):
		result = request1.GET("${url}")

		# result is a HTTPClient.HTTPResult. 
		# We get the message body using the getText() method.
		# assert result.getText().find("HELLO WORLD") != -1;
		
		# if you want to print out log.. 
		# Don't use print keyword. This will make the output lost.
		# instead use following.
		# grinder.logger.info("Hello World")
		
		assert result.getStatusCode() == 200
        