# -*- coding:utf-8 -*-

# A simple example using the HTTP plugin that shows the retrieval of a
# single page via HTTP.
#
# This script is automatically generated by ngrinder.
#
# @author your_name
from net.grinder.script.Grinder import grinder
from net.grinder.script import Test
from net.grinder.plugin.http import HTTPRequest
from net.grinder.plugin.http import HTTPPluginControl
from java.util import Date
from HTTPClient import NVPair, Cookie, CookieModule

control = HTTPPluginControl.getConnectionDefaults()
# if you don't want that HTTPRequest follows the redirection, please modify the following option 0.
# control.followRedirects = 1
# if you want to increase the timeout, please modify the following option.
control.timeout = 6000

test1 = Test(1, "HAR2Script")
request = HTTPRequest()

# Set header datas
headers = [] # Array of NVPair
<#if commonHeader?? && commonHeader?size != 0>
	# Common Headers
	<#assign keys = commonHeader?keys>
	<#list keys as key>
headers.append(NVPair("${key}", "${commonHeader[key]?replace("$", "\\$")}"))
	</#list>
</#if>

class TestRunner:
    # initlialize a thread
    def __init__(self):
        test1.record(TestRunner.__call__)
        grinder.statistics.delayReports=True
        pass

    def before(self):
        request.headers = headers

    # test method
    def __call__(self):
        self.before()

        # Choose of Request
<#if requests??>
	<#list requests as request>
        postData_${request_index} = [];
        perRequestHeaders_${request_index} = [];
		<#if request.postData?? && request.postData?size != 0>
			<#assign keys = request.postData?keys>
			<#list keys as key>
        postData_${request_index}.append(NVPair("${key}", "${request.postData[key]?replace("$", "\\$")}"))
			</#list>
		</#if>
		<#if request.headers?? && request.headers?size != 0>
			<#assign keys = request.headers?keys>
			<#list keys as key>
        perRequestHeaders_${request_index}.append(NVPair("${key}", "${request.headers[key]?replace("$", "\\$")}"))
			</#list>
		</#if>
        result = request.${request.method?default("GET")}("${request.url}",postData_${request_index} ,perRequestHeaders_${request_index})

	</#list>
</#if>

        # You get the message body using the getText() method.
        # if result.getText().find("HELLO WORLD") == -1 :
        #	 raise

        # if you want to print out log.. Don't use print keyword. Instead, use following.
        # grinder.logger.info("Hello World")

        if result.getStatusCode() == 200 :
            return
        elif result.getStatusCode() in (301, 302) :
            grinder.logger.warn("Warning. The response may not be correct. The response code was %d." %  result.getStatusCode())
            return
        else :
            raise



