{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ngrinder",
    "module": "ngrinder-groovy",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ftklc5dtezgpnbhiluq7gqole4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ngrinder",
          "module": "ngrinder-runtime",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ngrinder-groovy-3.5.0.jar",
          "url": "ngrinder-groovy-3.5.0.jar",
          "size": 43145,
          "sha512": "f6c27b66d9f488eed04345bae671aedb8aa73cb202eaa21661d45d476068ab90b28b14d4517cea03927733256b0256ef258a967f127d6536c8a5cb31e2a2c896",
          "sha256": "0583d3f46b4a2b024398c052fa6ba2afc25bd1c36687a560e1177e1ab2c50477",
          "sha1": "ab2ffc0992d4eb0c891deda740d52725e7264c69",
          "md5": "bcd8fce0cb383a7b43a0fe3c836ac9ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ngrinder",
          "module": "ngrinder-runtime",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ngrinder-groovy-3.5.0.jar",
          "url": "ngrinder-groovy-3.5.0.jar",
          "size": 43145,
          "sha512": "f6c27b66d9f488eed04345bae671aedb8aa73cb202eaa21661d45d476068ab90b28b14d4517cea03927733256b0256ef258a967f127d6536c8a5cb31e2a2c896",
          "sha256": "0583d3f46b4a2b024398c052fa6ba2afc25bd1c36687a560e1177e1ab2c50477",
          "sha1": "ab2ffc0992d4eb0c891deda740d52725e7264c69",
          "md5": "bcd8fce0cb383a7b43a0fe3c836ac9ca"
        }
      ]
    }
  ]
}
