[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="maxRunHour" type="java.lang.Number" --]
[#-- @ftlvariable name="currentUser" type="org.ngrinder.model.User" --]
[#-- @ftlvariable name="test" type="org.ngrinder.model.PerfTest" --]
