[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="user" type="org.ngrinder.model.User" --]
[#-- @ftlvariable name="breadcrumbPath" type="java.lang.String" file="../webapp/WEB-INF/ftl/script/editor.ftl" --]
[#-- @ftlvariable name="scriptHandler" type="org.ngrinder.script.handler.ScriptHandler" file="../webapp/WEB-INF/ftl/script/editor.ftl" --]
[#-- @ftlvariable name="file" type="org.ngrinder.script.model.FileEntry" file="../webapp/WEB-INF/ftl/script/editor.ftl" --]
[#-- @ftlvariable name="script" type="java.lang.String" file="../webapp/WEB-INF/ftl/operation/script_console.ftl" --]
[#-- @ftlvariable name="announcement_hide" type="java.lang.String" file="../webapp/WEB-INF/ftl/common/navigator.ftl" --]
[#-- @ftlvariable name="announcement" type="java.lang.String" file="../webapp/WEB-INF/ftl/common/navigator.ftl" --]
[#-- @ftlvariable name="plugins" type="java.util.List" file="../webapp/WEB-INF/ftl/perftest/detail_report.ftl" --]
[#-- @ftlvariable name="query" type="java.lang.String" file="../webapp/WEB-INF/ftl/script/list.ftl" --]
[#-- @ftlvariable name="svnUrl" type="String" file="../webapp/WEB-INF/ftl/script/list.ftl" --]
[#-- @ftlvariable name="files" type="java.util.List" file="../webapp/WEB-INF/ftl/script/list.ftl" --]
[#-- @ftlvariable name="currentPath" type="java.lang.String" file="../webapp/WEB-INF/ftl/script/list.ftl" --]
[#-- @ftlvariable name="regionAgentCountMap" type="java.util.Map" file="../webapp/WEB-INF/ftl/perftest/detail.ftl" --]
[#-- @ftlvariable name="regions" type="java.util.List<Region>" file="../webapp/WEB-INF/ftl/perftest/config.ftl" --]
[#-- @ftlvariable name="maxVuserPerAgent" type="int" file="../webapp/WEB-INF/ftl/perftest/config.ftl" --]
[#-- @ftlvariable name="quickScript" type="String" file="../webapp/WEB-INF/ftl/perftest/config.ftl" --]
[#-- @ftlvariable name="quickScriptRevision" type="long" file="../webapp/WEB-INF/ftl/perftest/config.ftl" --]
[#-- @ftlvariable name="maxRunCount" type="java.lang.Number" --]
[#-- @ftlvariable name="safeFileDistribution" type="boolean" --]
[#-- @ftlvariable name="targetIP" type="String" file="../webapp/WEB-INF/ftl/monitor/info.ftl" --]
[#-- @ftlvariable name="clustered" type="Boolean" --]
[#-- @ftlvariable name="req" type="javax.servlet.http.HttpServletRequest" --]
[#-- @ftlvariable name="nGrinderVersion" type="java.lang.String" --]
[#-- @ftlvariable name="maxRunHour" type="java.lang.Number" --]
[#-- @ftlvariable name="currentUser" type="org.ngrinder.model.User" --]
[#-- @ftlvariable name="test" type="org.ngrinder.model.PerfTest" --]
