{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ngrinder",
    "module": "ngrinder-groovy",
    "version": "3.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ofrirs4ernb6vhtba2zp2mmqbe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ngrinder",
          "module": "ngrinder-runtime",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.5"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-datetime",
          "version": {
            "requires": "3.0.5"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-templates",
          "version": {
            "requires": "3.0.5"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-json",
          "version": {
            "requires": "3.0.5"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-sql",
          "version": {
            "requires": "3.0.5"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "ngrinder-groovy-3.5.2.jar",
          "url": "ngrinder-groovy-3.5.2.jar",
          "size": 43020,
          "sha512": "89d0f5682377c7a535abdc5dcf7ad9cafd3b2d9996bc0cc05d91f8bdb548d29d6115065db880c5dad351bdf4b3deb1fc1825d95643e9063bd79017af96456f22",
          "sha256": "a47ef0aa399fef9d9ff277378d7f52436c941f2ef8f826f8fe61ef1b1162a607",
          "sha1": "9b25636cb5fe4230043f771dde246a90c0c058be",
          "md5": "655fc1a510b0c94ef14f6b5e443e9e9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ngrinder",
          "module": "ngrinder-runtime",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.5"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-datetime",
          "version": {
            "requires": "3.0.5"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-templates",
          "version": {
            "requires": "3.0.5"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-json",
          "version": {
            "requires": "3.0.5"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-sql",
          "version": {
            "requires": "3.0.5"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "ngrinder-groovy-3.5.2.jar",
          "url": "ngrinder-groovy-3.5.2.jar",
          "size": 43020,
          "sha512": "89d0f5682377c7a535abdc5dcf7ad9cafd3b2d9996bc0cc05d91f8bdb548d29d6115065db880c5dad351bdf4b3deb1fc1825d95643e9063bd79017af96456f22",
          "sha256": "a47ef0aa399fef9d9ff277378d7f52436c941f2ef8f826f8fe61ef1b1162a607",
          "sha1": "9b25636cb5fe4230043f771dde246a90c0c058be",
          "md5": "655fc1a510b0c94ef14f6b5e443e9e9d"
        }
      ]
    }
  ]
}
