{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ngrinder",
    "module": "ngrinder-runtime",
    "version": "3.5.1-p1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "b4j4hk3qafdmfg7bsqgimwbkfa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20090211"
          }
        },
        {
          "group": "dnsjava",
          "module": "dnsjava",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "commons-lang",
          "module": "commons-lang",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest-all",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "junit",
          "module": "junit-dep",
          "version": {
            "requires": "4.8.2"
          }
        },
        {
          "group": "asm",
          "module": "asm",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "net.sf.grinder",
          "module": "grinder",
          "version": {
            "requires": "3.9.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "grinder-xmlbeans"
            },
            {
              "group": "*",
              "module": "jython"
            },
            {
              "group": "*",
              "module": "clojure"
            },
            {
              "group": "*",
              "module": "jedit-syntax"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ngrinder-runtime-3.5.1-p1.jar",
          "url": "ngrinder-runtime-3.5.1-p1.jar",
          "size": 55152,
          "sha512": "19313797836505aead899fe40062a82ceee876f3956e565447ace33080c5854b5c0dd4c8dbd31bf2a452fdf582c1b3ad7f74dec815ae5e79dcdedcdabce88f4c",
          "sha256": "78074535f3e83aba9063db8ecefb1a58f06eaa67015c8dcd2710dd690d0ac976",
          "sha1": "22282180b534485fd4ee43b668920e1ab3a7ba44",
          "md5": "1c8565285c4dbb4c38ed9687ef542750"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20090211"
          }
        },
        {
          "group": "dnsjava",
          "module": "dnsjava",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "commons-lang",
          "module": "commons-lang",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest-all",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "junit",
          "module": "junit-dep",
          "version": {
            "requires": "4.8.2"
          }
        },
        {
          "group": "asm",
          "module": "asm",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "net.sf.grinder",
          "module": "grinder",
          "version": {
            "requires": "3.9.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "grinder-xmlbeans"
            },
            {
              "group": "*",
              "module": "jython"
            },
            {
              "group": "*",
              "module": "clojure"
            },
            {
              "group": "*",
              "module": "jedit-syntax"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ngrinder-runtime-3.5.1-p1.jar",
          "url": "ngrinder-runtime-3.5.1-p1.jar",
          "size": 55152,
          "sha512": "19313797836505aead899fe40062a82ceee876f3956e565447ace33080c5854b5c0dd4c8dbd31bf2a452fdf582c1b3ad7f74dec815ae5e79dcdedcdabce88f4c",
          "sha256": "78074535f3e83aba9063db8ecefb1a58f06eaa67015c8dcd2710dd690d0ac976",
          "sha1": "22282180b534485fd4ee43b668920e1ab3a7ba44",
          "md5": "1c8565285c4dbb4c38ed9687ef542750"
        }
      ]
    }
  ]
}
